language: php

php:
  - 5.6
  - 7.0

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer self-update --snapshot
  - composer update $COMPOSER_OPTS

script:
  - ./tests/lint.sh
  - ./bin/sonos

git:
  depth: 5
